<a href="https://colab.research.google.com/github/mackon1705/data-science-bootcamp/blob/main/Rozdzial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [ ]:
#Tablice - podstawowy obiekt numpy, kazdy element tego samego typu, wymiary - osie(axes), klasa 1D Array
help(np.array)

In [ ]:
#1D Array
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
#atrybuty ndarray - wymiar tablicy
x.ndim

1

In [ ]:
#ksztalt ndarray (zwraca tuple)
x.shape

(2,)

In [ ]:
# liczba elementow w ndarray
x.size

2

In [ ]:
# typ danych w ndarray
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.size

3

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x.shape

(3,)

Tablica 2D Array

In [ ]:
#macierz
x = np.array([[1,2],[-3, 1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([[1,2,4],[4,2,5]])
print(y)

[[1 2 4]
 [4 2 5]]


In [ ]:
y.shape

(2, 3)

Tablica trojwymiarowa (przechowywanie danych np. obraz)

In [ ]:
x = np.array(
    [[[1,2,3],
     [2,3,4]],

     [[2,3,5],
      [3,5,7]]]
)
x

array([[[1, 2, 3],
        [2, 3, 4]],

       [[2, 3, 5],
        [3, 5, 7]]])

In [ ]:
x.ndim

3

In [ ]:
# 2 tablice, 2 wiersze, 3 kolumny
x.shape

(2, 2, 3)

###Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
B = np.array([1.0,2.7,3.8])
B.dtype

dtype('float64')

In [ ]:
#Kontrolowanie typu
C = np.array([1.4,2.3,6.7], dtype='float')
print(C)

[1.4 2.3 6.7]


In [ ]:
C

array([1.4, 2.3, 6.7])

In [ ]:
#Kontrolowanie typu. - liczby zlozone
D = np.array([1.4,2.3,6.7], dtype='complex')
print(D)

[1.4+0.j 2.3+0.j 6.7+0.j]


In [ ]:
#Odwrotna operacja
E = np.array([1.4,2.3,6.7], dtype='int')
print(E)
E.dtype

[1 2 6]


dtype('int64')

In [ ]:
F = np.array([True, False])
F.dtype

dtype('bool')

In [ ]:
# Tablica obrazu - 8 bitowa mapa (zajmie mniej miejsca)
G = np.array([24,120,230], dtype=np.int8)
G.dtype

dtype('int8')

In [ ]:
# Tablica obrazu - od 0 do 255
H = np.array([24,120,230], dtype=np.uint8)
H.dtype

dtype('uint8')

###Tworzenie tablic

In [ ]:
# Tablica z samymi zerami - 4 wiersze 10 kolumn, domyslnie float
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#Tworzenie masek do zdjec (zdjecie 600x800 z czrnym tlem - numpy zeros)

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# uzupelnianie dana wartoscia
np.full(shape=(3,3), fill_value=6, dtype='int')

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [ ]:
# Dane od zera od 10 (bez)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=20, step=2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(start=100, stop=20, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
#Ile parametrow potrzebujemy (rowno rozlozone)
np.linspace(start=0, stop=1, num=8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#zzmiana rozmiaru danych - tablica 3x5
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 3 wiersze i niech python dopasu
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# 3 kolumny i niech wiersze python dopasuje
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Operacje na tablicach

In [ ]:
A = np.array([3,1,4,2])
B = np.array([1,-3,2,3])
print(A)
print(B)

[3 1 4 2]
[ 1 -3  2  3]


In [ ]:
A + B

array([ 4, -2,  6,  5])

In [ ]:
A - B

array([ 2,  4,  2, -1])

In [ ]:
A * B

array([ 3, -3,  8,  6])

In [ ]:
# Tablica nie moze miec zera
A / B

array([ 3.        , -0.33333333,  2.        ,  0.66666667])

In [ ]:
# Dodawanie stałej do kazdego wiersz
A + 3

array([6, 4, 7, 5])

In [ ]:
A *2

array([6, 2, 8, 4])

In [ ]:
abs(A)

array([3, 1, 4, 2])

In [ ]:
A + 3*B

array([ 6, -8, 10, 11])

In [ ]:
#metody z numpy
np.add(A,B)

array([ 4, -2,  6,  5])

In [ ]:
np.subtract(A,B)

array([ 2,  4,  2, -1])

In [ ]:
np.multiply(A,B)

array([ 3, -3,  8,  6])

In [ ]:
np.divide(A,B)

array([ 3.        , -0.33333333,  2.        ,  0.66666667])

In [ ]:
#Mnozenie macierzowe

In [ ]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
#zwykle mnozenie
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
#mnozenie macierzy
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
# mnozenie macierzy inna opcja
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
#Mnozenie macierzy - inna opcja
X @ Y

array([[  3,   6],
       [-12,   0]])

### Liczby pseudolosowe

In [ ]:
#Ustawienie ziarna losowania
np.random.seed(0)

In [ ]:
#Losowy rozklad normalny standardowy, srednia 0, odchylenie 1
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
#10 wierszy 4 kolumny
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
#rozklad jednostajny na przedziale (0 domkniete, 1 jest wylaczone)
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10,3)

array([[0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947],
       [0.4686512 , 0.97676109, 0.60484552],
       [0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609]])

In [ ]:
#Funkcja randint (mniejsza od 10)
np.random.randint(10)

3

In [ ]:
#losowana liczba 2 cyfrowa
np.random.randint(low = 10, high = 101, size =10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
#Zwraca losowy element z listy
np.random.choice([4,2,1,4])

4

In [ ]:
np.random.choice(['A','Java','sql'])

'sql'

In [ ]:
#elementow
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#talowanie
np.random.shuffle(data)

In [ ]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

#Podstawowe funkcje w numpy

In [ ]:
#funckja exponent dla 1 jest stala Eulera
np.exp(1)

2.718281828459045

In [ ]:
np.exp(10)

22026.465794806718

In [ ]:
np.sqrt(9)

3.0

In [ ]:
#Sprawdza czy wraca false czy true (jak wszystkie true to true)
np.all([2,3,1])

True

In [ ]:
# Zwraca prawde jesli jedna jest prawda
np.any([1, 2, 1])

True

In [ ]:
bool(0)

False

In [ ]:
bool(1)

True

In [ ]:
A = np.random.rand(5)
A

array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287])

In [ ]:
#indeks gdzie tablica jest max
np.argmax(A)

3

In [ ]:
#wyciecie z tablice
A[np.argmax(A)]

0.8811031971111616

In [ ]:
np.argmin(A)

0

In [ ]:
#sortowanie po indeksie 0 najmniejsza, 3 to maksymalna wartosc (indeks)
np.argsort(A)

array([0, 2, 4, 1, 3])

In [ ]:
#maksymalna
np.max(A)

0.8811031971111616

In [ ]:
#srednia
np.mean(A)

0.5940233162303231

In [ ]:
#mediana
np.median(A)

0.5812728726358587

In [ ]:
#odchylenie standardowe
np.std(A)

0.2270924608641256

### Indeksowanie tablic

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#Wycinanie A[indeks do wycicia (od0)] lub przedział A[start:stop] , A[:stop], A[start:]


In [4]:
A[2]

2

In [7]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
A[:2]

array([0, 1])

In [9]:
A[[0,2]]

array([0, 2])

In [10]:
A[-1]

19

In [11]:
A[10:15]

array([10, 11, 12, 13, 14])

In [14]:
#zmiana wymiaruy tablicy
A= A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
#wycynanie wiersza
A[0]

array([0, 1, 2, 3, 4])

In [17]:
#wycinanie kolumny
A[:,0]

array([ 0,  5, 10, 15])

In [18]:
A[:, -1]

array([ 4,  9, 14, 19])

In [19]:
#wycinanie dokładnie danego elemenut
A[1,1]

6

In [20]:
A[1,3]

8

In [22]:
#wycinaie fragmentu
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [24]:
#Przypisywanie nowej wartosci
A[1,2] = 14

In [25]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach

In [26]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [28]:
#printujemy wyraz 0 kazdego wiesza
for row in A:
  print(row[0])

0
5
10
15


In [29]:
#flat - wyplaszczenie tablicy
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
#Zmiana rozmiaru tablic


In [30]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
A.shape

(4, 5)

In [32]:
#reshape
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
# ravel - wyplaszczenie danych, arange -> shape -> ravel
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
#transponowanie tablicy

In [36]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [37]:
#Maski logiczne
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
B = np.arange(start = -10, stop =10, step=0.5)
B = B.reshape(10,-1)
B

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [44]:
# wktorych miejscach wartosci ujemne
B > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
# wycinamy tylko dodatnie
B[B >0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [48]:
#maska z przedziałami bitwise and pozwala na sumowanie warunków
np.bitwise_and(B > -5, B <5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
np.bitwise_or(B < -5, B >5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])