<a href="https://colab.research.google.com/github/mackon1705/data-science-bootcamp/blob/main/Rozdzial1_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.5


In [ ]:
# norma wektora - pierwiastek sumy kwadratów współrzędnich (odległość euklidesowa od środka układu współrzędnicyhb)

In [5]:
v1 = np.array([-1,4])
v1

array([-1,  4])

Obliczanie normy wektora v1

In [6]:
np.linalg.norm(v1)

4.123105625617661

Norma eklidesowa w przystrzeni Rn (nauczanie maszynowe ma klikaset przestrzeni

In [7]:
v2 = np.array([-10,10,13])

In [9]:
np.linalg.norm(v2)

19.209372712298546

Odlegloc 2 punktow na plaszczyznie (roznica po wspolrzednych)

In [10]:
p = np.array([3,0])
q= np.array([0,4])

In [11]:
np.linalg.norm(p-q)

5.0

In [12]:
p = np.array([3,0,1])
q= np.array([0,4,2])

In [13]:
np.linalg.norm(p-q)

5.0990195135927845

MNOŻENIE MACIERZY

In [20]:
X = np.array([[5,3],[3,9]])
Y = np.array([[-1],[1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[-1]
 [ 1]]


In [23]:
Z = X.dot(Y)
Z1 = np.dot(X,Y)
print(Z)
print('\n')
print(Z1)

[[-2]
 [ 6]]


[[-2]
 [ 6]]


Wyznacznik macierzy - wyznacznik liczy jako zmiennoprzecinkowa - konieczne jest round

In [26]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

Ślad macierzy - suma elementów na przekątnej

In [27]:
A = np.array([[2,4], [-1,3]])
print(np.trace(A))

5


Macierz jednostkowa 

In [29]:
B = np.eye(5, dtype='int')
B

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna (macierz A musi byc kwadratorwa

In [34]:
C = np.linalg.inv(A)
print(np.dot(A,C))

[[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00]]


Ustawienie printowania dla biblioteki numpy

In [35]:
np.set_printoptions(precision=4, suppress=True)
print(np.dot(A,C))

[[1. 0.]
 [0. 1.]]


In [36]:
print(np.dot(C,A))

[[ 1. -0.]
 [ 0.  1.]]


Macierz transponowana (zamiana wierszy na kolumny, kolumny na wiersze

In [38]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

Inny sposób transponowania

In [39]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Układy równań

In [41]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [45]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [46]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]


In [47]:
X = np.dot(A_inv,B)
print(X)

[[1.]
 [2.]]


In [48]:
X.shape

(2, 1)